services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_listings
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data:
